[[edge_functions]]
  path = "/api/v1/sync/data"
  function = "tunnel"

[[edge_functions]]
  path = "/api/v1/sync/data/*"
  function = "tunnel"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
