# این بخش درخواست‌های تونل رو می‌فرسته سمت اسکریپت فیلترشکن
[[edge_functions]]
  path = "/p4r34m/*"
  function = "tunnel"

# این بخش بقیه درخواست‌ها رو می‌فرسته سمت سایت رزومه (برای رد گم کنی)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
